### ISSUE TITLE
Project Dependency hugo-installer Doesn’t Support Hugo Versions Above v0.101.0

### ISSUE THREAD

**Issue by kevinjcharles** [gethyas/hyas#332]
## Description

The hugo-development team has merged their hugo arm and intel releases into a single universal binary. Project dependency hugo-installer is broken as a result, and It is unclear if the hugo-installer project is still actively maintained.

### Steps to reproduce

Bump Hugo to any version above v0.101.0 and run npm install.

### Expected result

Specified Hugo version should be fetched and installed.

### Actual result

An error is thrown detailing that an appropriate Hugo binary could not be found.

### Environment

> Checking for existing binary
> Downloading binary from "https://github.com/gohugoio/hugo/releases/download/v0.102.0/hugo_extended_0.102.0_macOS-ARM64.tar.gz"
Error: An error occured while trying to download the binary from "https://github.com/gohugoio/hugo/releases/download/v0.102.0/hugo_extended_0.102.0_macOS-ARM64.tar.gz". Details: Response code 404 (Not Found)

**Comment by h-enk** [comment]
To be solved upstream

https://github.com/dominique-mueller/hugo-installer/issues/49

**Comment by h-enk** [comment]
Fixed: https://github.com/dominique-mueller/hugo-installer/issues/49#issuecomment-1245654329
