### ISSUE TITLE
Unused configuration parameters

### ISSUE THREAD

**Issue by AminZibayi** [gethyas/hyas#336]
## Description

The configuration parameters `bgColor` and `quality` are defined but never used.
Is `bgColor` intended to set `site.webmanifest`'s background_color property?

**Comment by h-enk** [comment]
I'm in the process of restructuring Hyas (technically I'm practically there, now updating documentation) — see also https://github.com/h-enk/hyas/pull/329

You're right — these settings are not used by the new @hyas/images module, they're temporarily left in place for backward compatibility. So, I will strip them out eventually,

**Comment by h-enk** [comment]
These parameters are part of Hugo's  default imaging [processing options](https://gohugo.io/content-management/image-processing/#processing-options) — and now also used with the [@hyas/images](https://github.com/gethyas/images)
