### ISSUE TITLE
Add --renderToDisk scripts

### ISSUE THREAD

**Issue by h-enk** [gethyas/hyas#411]
## Summary

Brief explanation of the feature.

`--renderToDisk`: serve all files from disk (default is from memory)

See also:
- [hugo-starters/default-template](https://github.com/hugo-starters/default-template)
- [hugo-starters/bootstrap-template](https://github.com/hugo-starters/bootstrap-template)
- [Hugo Tips: Avoid Crashes With '--renderToDisk'](https://jeremypedersen.com/posts/2022-03-02-hugo-draft-tip/)

### Basic example

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by flexxgaad** [comment]
Render to Disk is now the default from Hugo 0.123.0.

**Comment by h-enk** [comment]
Resource: [hugo server](https://gohugo.io/commands/hugo_server/)

**Comment by h-enk** [comment]
Now using `hugo server --disableFastRender --noHTTPCache"` with [v2.3.0](https://github.com/gethyas/hyas/releases/tag/v2.3.0)
