### ISSUE TITLE
Embedded YouTube video iframe invisible in production build

### ISSUE THREAD

**Issue by keybits** [gethyas/hyas#417]
## Description

I have the following code in my home page to show a YouTube video:

```
<section class="section section-md section-features">
  <div class="container">
    <div class="ratio ratio-16x9">
      <iframe
        src="https://www.youtube-nocookie.com/embed/0KtiJdZsAnI"
        title="PostOwl in one minute"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;"
        allowfullscreen=""
      ></iframe>
    </div>
  </div>
</section>
```

This displays a YouTube video as expected in dev mode.

When I build for production and serve the site from `public` the video isn't visible.

### Steps to reproduce

- Install hyas with latest doks theme: `npm create hyas@latest -- --template doks`
- add the code above somewhere in `themes/my-doks-theme/layouts/index.html`
- run `npm run dev` and see the video
- run `npm run build` and view the output of the public directory using a local web server and the video doesn't display.

### Live example

Example deployed on Cloudflare Pages at https://postowl-website.pages.dev/ - inspect and search for `iframe` and you'll see the code is there and the YouTube player has been downloaded, but it doesn't display.

(There's a warning in the console `Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'` but I believe that's just a warning and [can be ignored as described here](https://stackoverflow.com/questions/76313405/iframe-error-with-ch-ua-form-factor-cookie-permission).)

### Expected result

The video should display as it does in dev.

### Environment

nodejs 18.16.0 - same resulted in multiple supported environments.
hyas 2.1.0

**Comment by h-enk** [comment]
Looks like a setting on Cloudflare side. Does this help: https://community.cloudflare.com/t/youtube-is-not-working-in-cloudflare-zero-trust/404577/2

**Comment by keybits** [comment]
Thanks for looking. I don't think it's Cloudflare specific - it's the same locally if I `npm run build` and then serve the built pages in public with a local web server.

**Comment by h-enk** [comment]
You could try adding `iframe` and/or `ratio` and `ratio-16x9` to the whitelist section of postcss.config

**Comment by keybits** [comment]
Thank you!

I tested and all that was needed was to add `ratio-16x9` to purgecss's safelist.
