### ISSUE TITLE
Hugo executable files are gone after adding custom dependencies

### ISSUE THREAD

**Issue by HU-Lee** [gethyas/hyas#434]
### Steps to reproduce
`yarn add [some package]`

I found it while following this article, adding `medium-zoom` :
https://github.com/gethyas/doks/discussions/545

### Description
`yarn add` command works fine,
but `node_modules/gethyas/node_modules/.bin/hugo/*` folder disappears after this process
and postinstall command fails.

`yarn dev` command does not work after this too.

### To recover
clean and re-install packages, including `node_modules` and etc. , resolves the error.
```
yarn run clean
yarn
```

### Opinion
I think it is better to fix postinstall process/command,
or give specific guide to users who wants to add custom modules to theme.

I'm newbie to Hugo and really like Doks theme. Thanks for reading!

### Environment
nodejs: v18.17.1
@hyas/doks-core: 1.0.7
gethyas: 2.2.0

**Comment by h-enk** [comment]
Confirmed — using yarn 1.22.19

I will be looking into this. Please use npm or pnpm for now (or temporarily accept the inconvenience )

**Comment by h-enk** [comment]
Known and (still) an open issue — see https://github.com/yarnpkg/yarn/issues/5476

**Comment by HU-Lee** [comment]
Linked yarn issue seems to relate with problems that postinstall command is not executed.

In my case, postinstall command works fine.
However, `node_modules` folder in gethyas module blows up and it fails to copy on root folder's `node_modules` folder.

```powershell
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@hyas/doks-core > gethyas > quicklink@2.3.0" has unmet peer dependency "react@^16.8.0".
warning "@hyas/doks-core > gethyas > quicklink@2.3.0" has unmet peer dependency "react-dom@^16.8.0".
[5/5] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ medium-zoom@1.0.8
info All dependencies
└─ medium-zoom@1.0.8
$ shx rm -rf ./node_modules/.bin/hugo && shx mkdir node_modules/.bin/hugo && shx cp node_modules/gethyas/node_modules/.bin/hugo/* node_modules/.bin/hugo
cp: no such file or directory: node_modules/gethyas/node_modules/.bin/hugo/*
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by h-enk** [comment]
> I'm not sure that it is possible to ignore node_modules/gethyas/node_modules folder while yarn cleaning process is running, and it can be other options too.

Ignoring in a `.yarnclean` file doesn't seem to work for me (I tried a few things)

Another option, a bit bold — but it works:

```bash
yarn clean:install && yarn
```

**Comment by HU-Lee** [comment]
I finally changed to use `npm` instead of `yarn` when I'm upgrading Doks to 1.0.7 -> 1.2.0
As mentioned before, no issue when setting up with `npm`

Hugo also follows it for example: 
https://gohugo.io/hosting-and-deployment/hosting-on-github/

It'll be better to specify on documents and other places that `npm` or `pnpm` is recommended, not `yarn`

This issue has been stale for a while by the way, so I'll close this issue.
