### ISSUE TITLE
It's generally polite to ask

### ISSUE THREAD

**Issue by gardner** [gethyas/hyas#473]
## Summary

It's generally polite to ask before installing a binary on someones system. It was pretty alarming to have it happen in a postinstall hook. I already had `hugo` installed. I updated the scripts in `package.json` to just use `hugo` and install it if it is required:

```json
"postinfo": "hugo version",
"postinstall": "which hugo || hugo-installer --version otherDependencies.hugo --extended --destination node_modules/.bin/hugo"
```

and everything works fine except my firewall prompted me to allow hugo to listen on 0.0.0.0. Why does is need to listen on every interface when I am doing local development?

So now, I have the impression that hyas doesn't really pay attention to security and I still haven't figured out what benefit hyas provides over just doing `npm init` and manually configuring my build pipeline with hugo.

**Comment by h-enk** [comment]
Hyas 2.3 (available soon) will no longer install Hugo locally in your project and will no longer listen on 0.0.0.0.

Hyas gives you a headstart with (opinionated) build processes already in place and integrations like Images and SEO just an `npm install` away. Unlike most Hugo setups, Hyas *only* uses npm (not Hugo Modules) to [explicitly declare and isolate dependencies](https://12factor.net/dependencies)

**Comment by gardner** [comment]
Thanks for the quick reply! I'll check back in after 2.3. Closing...
